/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Sebastian Murrieta Verduzco -233463
 */
public class Entrar extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Entrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        insertarBtn = new javax.swing.JLabel();
        entrarBtn = new controlador.PanelRound();
        entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(24, 40, 54));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        insertarBtn.setForeground(new java.awt.Color(159, 159, 159));
        insertarBtn.setText("Inserción masiva");
        insertarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertarBtnMouseClicked(evt);
            }
        });
        Fondo.add(insertarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 240, -1));

        entrarBtn.setBackground(new java.awt.Color(81, 137, 161));
        entrarBtn.setCursorHandEnabled(true);
        entrarBtn.setRoundBottomLeft(50);
        entrarBtn.setRoundBottomRight(50);
        entrarBtn.setRoundTopLeft(50);
        entrarBtn.setRoundTopRight(50);
        entrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarBtnMouseClicked(evt);
            }
        });

        entrar.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("Entrar");

        javax.swing.GroupLayout entrarBtnLayout = new javax.swing.GroupLayout(entrarBtn);
        entrarBtn.setLayout(entrarBtnLayout);
        entrarBtnLayout.setHorizontalGroup(
            entrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entrarBtnLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(entrar)
                .addGap(104, 104, 104))
        );
        entrarBtnLayout.setVerticalGroup(
            entrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entrarBtnLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Fondo.add(entrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 310, 60));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertarBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_insertarBtnMouseClicked

    private void entrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBtnMouseClicked
        new Principal().setVisible(true);
    }//GEN-LAST:event_entrarBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel entrar;
    private controlador.PanelRound entrarBtn;
    private javax.swing.JLabel insertarBtn;
    // End of variables declaration//GEN-END:variables
}
